CREATE TABLE IF NOT EXISTS security_device_action_jobs (
    job_id TEXT PRIMARY KEY,
    status TEXT NOT NULL,
    action_type TEXT NOT NULL,
    device_ids_json TEXT NOT NULL,
    device_names_json TEXT NOT NULL DEFAULT '[]',
    reason TEXT NOT NULL DEFAULT '',
    params_json TEXT NOT NULL DEFAULT '{}',
    requested_by_email TEXT NOT NULL,
    requested_by_name TEXT NOT NULL DEFAULT '',
    requested_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    progress_current INTEGER NOT NULL DEFAULT 0,
    progress_total INTEGER NOT NULL DEFAULT 0,
    progress_message TEXT NOT NULL DEFAULT '',
    success_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    error TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_security_device_action_jobs_requested_at
    ON security_device_action_jobs(requested_at DESC);

CREATE TABLE IF NOT EXISTS security_device_action_job_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL,
    device_id TEXT NOT NULL,
    device_name TEXT NOT NULL DEFAULT '',
    azure_ad_device_id TEXT NOT NULL DEFAULT '',
    success INTEGER NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    error TEXT NOT NULL DEFAULT '',
    before_summary_json TEXT NOT NULL DEFAULT '{}',
    after_summary_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_security_device_action_job_results_job
    ON security_device_action_job_results(job_id, id);
