CREATE TABLE IF NOT EXISTS security_device_action_job_batches (
    batch_id TEXT PRIMARY KEY,
    requested_by_email TEXT NOT NULL,
    requested_by_name TEXT NOT NULL DEFAULT '',
    requested_at TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    item_count INTEGER NOT NULL DEFAULT 0,
    destructive_device_count INTEGER NOT NULL DEFAULT 0,
    destructive_device_names_json TEXT NOT NULL DEFAULT '[]',
    error TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_security_device_action_job_batches_requested_at
    ON security_device_action_job_batches(requested_at DESC);

CREATE TABLE IF NOT EXISTS security_device_action_batch_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id TEXT NOT NULL,
    child_job_id TEXT NOT NULL,
    device_id TEXT NOT NULL,
    device_name TEXT NOT NULL DEFAULT '',
    action_type TEXT NOT NULL,
    assignment_user_id TEXT NOT NULL DEFAULT '',
    assignment_user_display_name TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_security_device_action_batch_items_batch
    ON security_device_action_batch_items(batch_id, id);
